[workspace]
members = [
    "api",
    "libs/*"
]

[workspace.dependencies]
sea-orm = "0.12.3"
tokio = "1.32.0"
reqwest = "0.11.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.49"

error.path = "libs/error"