version: '3.1'

services:
  crypto-issues:
    build: 
      dockerfile: Dockerfile
      context: backend
    restart: no
    environment:
      DATABASE_URL: postgres://postgres:password@database:5666/crypto-issues
    ports:
      - 1111:1111
    extra_hosts:
      - "database:host-gateway"