version: '3.1'

services:
  api:
    build: 
      dockerfile: Dockerfile
      context: backend
    restart: no
    environment:
      DATABASE_URL: postgres://postgres:password@database:5666/crypto-issues
    ports:
      - 1111:1111
    extra_hosts:
      - "database:host-gateway"

  frontend:
    build: 
      dockerfile: Dockerfile
      context: frontend
    restart: always
    environment:
      API_URL: http://api-url:1111
    ports:
      - 9000:80
    extra_hosts:
      - "api-url:host-gateway"

  