//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cryptocurrencies")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub coingecko_id: String,
    pub github: Option<Uuid>,
    pub gitlab: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::github_projects::Entity",
        from = "Column::Github",
        to = "super::github_projects::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    GithubProjects,
}

impl Related<super::github_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GithubProjects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
