//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "github_projects")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub profile_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub url: Option<String>,
    pub followers: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cryptocurrencies::Entity")]
    Cryptocurrencies,
    #[sea_orm(has_many = "super::github_repositories::Entity")]
    GithubRepositories,
}

impl Related<super::cryptocurrencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cryptocurrencies.def()
    }
}

impl Related<super::github_repositories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GithubRepositories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
