//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "github_repositories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub project: Option<String>,
    pub repository_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cryptocurrencies::Entity",
        from = "Column::Project",
        to = "super::cryptocurrencies::Column::Github",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Cryptocurrencies,
}

impl Related<super::cryptocurrencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cryptocurrencies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
