//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "issues")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub repository: Uuid,
    pub issue: i64,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTime,
    pub closed: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::github_repositories::Entity",
        from = "Column::Repository",
        to = "super::github_repositories::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GithubRepositories,
}

impl Related<super::github_repositories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GithubRepositories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
