name: Rust

on:
  push:
    branches: ["master"]
    

env:
  CARGO_TERM_COLOR: always

jobs:
  api-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: crypto-issues
        ports:
          - 5432:5432
    container:
      image: xd009642/tarpaulin:develop-nightly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate code coverage
        env: 
          DATABASE_URL: postgres://postgres:password@localhost:5432/crypto-issues
        run: |
          cargo tarpaulin --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error:     true