name: Vue

on:
  push:
    paths:
      - "backend/**"
    
env:
  CARGO_TERM_COLOR: always

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Run tests
        run: |
          cd frontend
          npm i
          npm run code-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend
          